#cargo-features = ["once_cell"]

[package]
name = "terraform-provider-cmd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = {version = "0.6", features = ["tls"] }
prost = "0.9"
futures = "0.3"
futures-core = "0.3"
futures-util = "0.3"
tokio = { version = "1.0", features = ["rt-multi-thread", "macros", "sync", "time"] }
tokio-stream = { version = "0.1.11", features = ["sync"] }

async-stream = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.7"

async-trait = "0.1"
anyhow = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["json", "fmt", "std"] }
rcgen = "0.10"
base64 = "0.13"
tower-http = {version = "0.1", features=["trace"] }
rustls = {version = "0.19", features=["dangerous_configuration"]}
webpki = "0.21"
x509-parser = "0.12"
time = "0.3"
pem = "1.1"

[build-dependencies]
tonic-build = "0.6"
